spring:
  cloud:
    gateway:
      routes:
        - id: user-service-public
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/users/login/**, /users/signup/**, /users/reissue

        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/users/**, /badges/**
          filters:
            - name: JwtAuthenticationFilter

        - id: store-service-internal
          uri: ${STORE_SERVICE_URL:http://store-service:8084}
          predicates:
            - Path=/internal/**

        - id: store-service-public
          uri: ${STORE_SERVICE_URL:http://store-service:8084}
          predicates:
            - Path=/points/**, /products/**
          filters:
            - name: JwtAuthenticationFilter

        - id: community-service
          uri: ${COMMUNITY_SERVICE_URL:http://community-service:8082}
          predicates:
            - Path=/inquiries/**,/notices/**
          filters:
            - name: JwtAuthenticationFilter

        - id: study-service-public
          uri: ${STUDY_SERVICE_URL:http://study-service:8083}
          predicates:
            - Method=GET
            - Path=/study-groups,/study-groups/recommended,/study-groups/*

        - id: study-service
          uri: ${STUDY_SERVICE_URL:http://study-service:8083}
          predicates:
            - Path=/study-groups/**
          filters:
            - name: JwtAuthenticationFilter

eureka:
  client:
    enabled: false
