server:
  port: 8082
spring:
  application:
    name: community-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: trace
    com.checkit.gatewayservice: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings